#requires -version 5.1
[CmdletBinding()]
param()
$ErrorActionPreference='SilentlyContinue'
$Version='0.2'; $Author='Mukamyi Izere Arcange'; $Name='Arcange Windows Technician Toolkit'
$Root=Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$ReportDir=Join-Path $Root 'reports'; New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
$LogFile=Join-Path $ReportDir ("session_{0}.log" -f (Get-Date -Format 'yyyyMMdd_HHmmss'))
function Log($m,$l='INFO'){Add-Content $LogFile ("{0} [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$l,$m)}
function Header{Clear-Host;Write-Host '';Write-Host '============================================================';Write-Host "       ARCANGE WINDOWS TECHNICIAN TOOLKIT v$Version";Write-Host '============================================================';Write-Host "Created by: $Author";Write-Host 'Supported OS: Windows 10 and Windows 11';Write-Host '============================================================';Write-Host ''}
function Pause-Toolkit{Read-Host 'Press Enter to continue'|Out-Null}
function Confirm($text){$x=Read-Host "$text [Y/N]";return $x -match '^(Y|YES)$'}
function Supported{$o=Get-CimInstance Win32_OperatingSystem;return [bool]($o.Caption -match 'Windows 10|Windows 11')}
function Admin{$p=[Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent();return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function SystemInfo{Header;Log 'Viewed system information';$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$p=Get-CimInstance Win32_Processor|select -First 1;$b=Get-CimInstance Win32_BIOS|select -First 1;Write-Host "Computer : $env:COMPUTERNAME";Write-Host "User     : $env:USERNAME";Write-Host "OS       : $($o.Caption)";Write-Host "Build    : $($o.BuildNumber)";Write-Host "CPU      : $($p.Name)";Write-Host "Cores    : $($p.NumberOfCores)";Write-Host "Threads  : $($p.NumberOfLogicalProcessors)";Write-Host ('RAM      : {0:N2} GB' -f ($c.TotalPhysicalMemory/1GB));Write-Host "BIOS     : $($b.Manufacturer) $($b.SMBIOSBIOSVersion)";Write-Host "Model    : $($c.Manufacturer) $($c.Model)";Write-Host "Admin    : $(Admin)";Pause-Toolkit}
function Hardware{Header;Log 'Ran hardware diagnostics';Write-Host '--- Problem Devices ---';$x=Get-PnpDevice|where Status -ne 'OK';if($x){$x|ft Status,Class,FriendlyName -AutoSize}else{Write-Host '[OK] No PnP devices currently report a problem.'};Write-Host '`n--- CPU ---';Get-CimInstance Win32_Processor|select Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed|ft -AutoSize;Write-Host '`n--- Memory ---';Get-CimInstance Win32_PhysicalMemory|select Manufacturer,PartNumber,@{N='CapacityGB';E={[math]::Round($_.Capacity/1GB,2)}},Speed|ft -AutoSize;Write-Host '`n--- GPU ---';Get-CimInstance Win32_VideoController|select Name,DriverVersion,Status|ft -AutoSize;Write-Host '`n--- USB ---';Get-PnpDevice -Class USB|select Status,FriendlyName,InstanceId|ft -AutoSize;Write-Host '`n--- Network Adapters ---';Get-NetAdapter|select Name,Status,LinkSpeed,InterfaceDescription|ft -AutoSize;Pause-Toolkit}
function Network{Header;Log 'Ran network diagnostics';Write-Host '--- Configuration ---';Get-NetIPConfiguration|select InterfaceAlias,IPv4Address,IPv4DefaultGateway,DNSServer|fl;Write-Host '--- Connectivity ---';foreach($t in '127.0.0.1','8.8.8.8'){if(Test-Connection $t -Count 2 -Quiet){Write-Host "[OK] $t reachable"}else{Write-Host "[FAIL] $t unreachable"}};Write-Host '--- DNS ---';try{Resolve-DnsName example.com -ErrorAction Stop|select -First 3 Name,Type,IPAddress|ft -AutoSize;Write-Host '[OK] DNS resolution works.'}catch{Write-Host '[FAIL] DNS resolution failed.'};Write-Host '--- HTTPS test ---';if(Test-NetConnection example.com -Port 443 -InformationLevel Quiet){Write-Host '[OK] HTTPS connection works.'}else{Write-Host '[FAIL] HTTPS connection failed.'};Write-Host '--- Route ---';route print;Pause-Toolkit}
function WindowsHealth{Header;Log 'Ran Windows health diagnostics';Write-Host '--- SFC verification (read-only) ---';sfc /verifyonly;Write-Host '--- DISM CheckHealth ---';dism /Online /Cleanup-Image /CheckHealth;Write-Host '--- Recent System Errors ---';Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-3)} -MaxEvents 15|select TimeCreated,Id,ProviderName,LevelDisplayName,Message|fl;Write-Host '--- Services not running (selected automatic services) ---';Get-CimInstance Win32_Service|where {$_.StartMode -eq 'Auto' -and $_.State -ne 'Running'}|select Name,DisplayName,StartMode,State|ft -AutoSize;Pause-Toolkit}
function Storage{Header;Log 'Ran storage diagnostics';Write-Host '--- Volumes ---';Get-Volume|select DriveLetter,FileSystem,HealthStatus,@{N='FreeGB';E={[math]::Round($_.SizeRemaining/1GB,2)}},@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}}|ft -AutoSize;Write-Host '`n--- Physical Disks ---';Get-PhysicalDisk|select FriendlyName,MediaType,HealthStatus,OperationalStatus,@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}}|ft -AutoSize;Write-Host '`n--- CHKDSK C: (read-only) ---';chkdsk C:;Pause-Toolkit}
function Drivers{Header;Log 'Ran driver diagnostics';Write-Host '--- Signed Driver Summary ---';driverquery /si;Write-Host '`n--- Problem Devices ---';Get-PnpDevice|where Status -ne 'OK'|select Status,Class,FriendlyName,InstanceId|ft -AutoSize;Write-Host '`n--- Driver Packages ---';pnputil /enum-drivers;Pause-Toolkit}
function Battery{Header;Log 'Ran battery diagnostics';$b=Get-CimInstance Win32_Battery;if($b){$b|select Name,BatteryStatus,EstimatedChargeRemaining,EstimatedRunTime|ft -AutoSize;Write-Host 'Generating Windows battery report...';$f=Join-Path $ReportDir ("battery_{0}.html" -f (Get-Date -Format 'yyyyMMdd_HHmmss'));powercfg /batteryreport /output $f|Out-Null;Write-Host "[OK] $f"}else{Write-Host '[INFO] No battery detected. This may be a desktop PC.'};Pause-Toolkit}
function Security{Header;Log 'Viewed security status';Write-Host '--- Firewall ---';Get-NetFirewallProfile|select Name,Enabled,DefaultInboundAction,DefaultOutboundAction|ft -AutoSize;Write-Host '--- Microsoft Defender ---';if(Get-Command Get-MpComputerStatus){Get-MpComputerStatus|select AMServiceEnabled,AntivirusEnabled,RealTimeProtectionEnabled,AntispywareEnabled,AntivirusSignatureVersion|ft -AutoSize}else{Write-Host '[INFO] Defender cmdlets unavailable.'};Pause-Toolkit}
function Repair{Header;Write-Host 'REPAIR CENTER - system changes require authorization.';if(-not(Admin)){Write-Host '[WARNING] Administrator privileges are recommended for repairs.'};Write-Host '1 Flush DNS';Write-Host '2 Renew DHCP';Write-Host '3 Reset Winsock';Write-Host '4 Reset TCP/IP';Write-Host '5 DISM RestoreHealth';Write-Host '6 SFC Scan';Write-Host '7 Restart Windows Explorer';Write-Host '0 Back';$c=Read-Host 'Choose';switch($c){'1'{if(Confirm 'Flush DNS cache?'){ipconfig /flushdns;Log 'Flushed DNS'}}'2'{if(Confirm 'Release and renew DHCP?'){ipconfig /release;ipconfig /renew;Log 'Renewed DHCP'}}'3'{if(Confirm 'Reset Winsock? A restart may be required.'){netsh winsock reset;Log 'Reset Winsock'}}'4'{if(Confirm 'Reset TCP/IP? A restart may be required.'){netsh int ip reset;Log 'Reset TCP/IP'}}'5'{if(Confirm 'Run DISM RestoreHealth? This can take time.'){dism /Online /Cleanup-Image /RestoreHealth;Log 'Ran DISM RestoreHealth'}}'6'{if(Confirm 'Run SFC /scannow?'){sfc /scannow;Log 'Ran SFC scan'}}'7'{if(Confirm 'Restart Windows Explorer?'){Stop-Process -Name explorer -Force;Start-Process explorer.exe;Log 'Restarted Explorer'}}};Pause-Toolkit}
function Report{Header;$f=Join-Path $ReportDir ("diagnostic_{0}.txt" -f (Get-Date -Format 'yyyyMMdd_HHmmss'));Log "Generated report $f";@("$Name v$Version","Created by: $Author","Generated: $(Get-Date)","Computer: $env:COMPUTERNAME","User: $env:USERNAME","Administrator: $(Admin)",'','=== OS ===',(Get-CimInstance Win32_OperatingSystem|select Caption,Version,BuildNumber,OSArchitecture,LastBootUpTime|fl|Out-String),'=== COMPUTER ===',(Get-CimInstance Win32_ComputerSystem|select Manufacturer,Model,SystemType,TotalPhysicalMemory|fl|Out-String),'=== CPU ===',(Get-CimInstance Win32_Processor|select Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed|fl|Out-String),'=== BIOS ===',(Get-CimInstance Win32_BIOS|select Manufacturer,SMBIOSBIOSVersion,ReleaseDate|fl|Out-String),'=== MEMORY ===',(Get-CimInstance Win32_PhysicalMemory|ft Manufacturer,PartNumber,Capacity,Speed|Out-String),'=== DISKS ===',(Get-Disk|ft Number,FriendlyName,OperationalStatus,HealthStatus,Size|Out-String),'=== VOLUMES ===',(Get-Volume|ft DriveLetter,FileSystem,HealthStatus,SizeRemaining,Size|Out-String),'=== NETWORK ===',(Get-NetIPConfiguration|fl|Out-String),'=== ADAPTERS ===',(Get-NetAdapter|ft Name,Status,LinkSpeed,InterfaceDescription|Out-String),'=== PROBLEM DEVICES ===',((Get-PnpDevice|where Status -ne 'OK')|ft Status,Class,FriendlyName,InstanceId|Out-String),'=== FIREWALL ===',(Get-NetFirewallProfile|ft Name,Enabled,DefaultInboundAction,DefaultOutboundAction|Out-String),'=== RECENT SYSTEM ERRORS ===',(Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-3)} -MaxEvents 20|select TimeCreated,Id,ProviderName,LevelDisplayName,Message|fl|Out-String))|Set-Content $f -Encoding UTF8;Write-Host "[OK] Report saved: $f";Pause-Toolkit}
function Main{if(-not(Supported)){Header;Write-Host '[UNSUPPORTED OS] Windows 10 and Windows 11 only.';Pause-Toolkit;return};Log "Toolkit started on $env:COMPUTERNAME";while($true){Header;Write-Host ' 1. System Information';Write-Host ' 2. Hardware Diagnostics';Write-Host ' 3. Network Diagnostics';Write-Host ' 4. Windows Health Diagnostics';Write-Host ' 5. Storage Diagnostics';Write-Host ' 6. Driver Diagnostics';Write-Host ' 7. Battery Diagnostics';Write-Host ' 8. Security Status';Write-Host ' 9. Repair Center';Write-Host '10. Generate Full Diagnostic Report';Write-Host '11. Open Reports Folder';Write-Host ' 0. Exit';Write-Host '';Write-Host "Administrator: $(Admin)";$c=Read-Host 'Select an option';switch($c){'1'{SystemInfo}'2'{Hardware}'3'{Network}'4'{WindowsHealth}'5'{Storage}'6'{Drivers}'7'{Battery}'8'{Security}'9'{Repair}'10'{Report}'11'{Start-Process explorer.exe $ReportDir}'0'{Header;Write-Host '============================================================';Write-Host '          THANK YOU FOR USING THIS SERVICE';Write-Host '============================================================';Write-Host "Arcange Windows Technician Toolkit v$Version";Write-Host "Created by: $Author";Write-Host '';Write-Host 'Thank you for using this service!';Write-Host 'Please keep your reports for future troubleshooting.';Log 'Toolkit session ended';return}default{Write-Host '[!] Invalid option.';Start-Sleep 1}}}}
Main
