#requires -version 5.1
[CmdletBinding()]
param([string]$Section='')
$ErrorActionPreference='SilentlyContinue'
$Version='0.5'
$Author='Mukamyi Izere Arcange'
$Name='Arcange Windows Technician Toolkit'
$Root=Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$ReportDir=Join-Path $Root 'reports'
New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
$SessionStamp=Get-Date -Format 'yyyyMMdd_HHmmss'
$CaseId='AWT-{0}' -f (Get-Date -Format 'yyyyMMdd-HHmmss')
$LogFile=Join-Path $ReportDir ("session_{0}.log" -f $SessionStamp)

function Log($m,$l='INFO'){Add-Content $LogFile ("{0} [{1}] [{2}] {3}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$CaseId,$l,$m)}
function Header{Clear-Host;Write-Host '';Write-Host '============================================================';Write-Host "       ARCANGE WINDOWS TECHNICIAN TOOLKIT v$Version";Write-Host '============================================================';Write-Host "Created by: $Author";Write-Host "Case ID: $CaseId";Write-Host "Manufacturer: $script:Manufacturer";Write-Host "Model: $script:Model";Write-Host 'Supported OS: Windows 10 and Windows 11';Write-Host '============================================================';Write-Host ''}
function Pause-Toolkit{Read-Host 'Press Enter to continue'|Out-Null}
function Confirm($text){$x=Read-Host "$text [Y/N]";return $x -match '^(Y|YES)$'}
function Supported{$o=Get-CimInstance Win32_OperatingSystem;return [bool]($o.Caption -match 'Windows 10|Windows 11')}
function Admin{$p=[Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent();return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Initialize-HardwareProfile{$c=Get-CimInstance Win32_ComputerSystem; if($c){$script:Manufacturer=if($c.Manufacturer){$c.Manufacturer.Trim()}else{'Unknown'};$script:Model=if($c.Model){$c.Model.Trim()}else{'Unknown'}}else{$script:Manufacturer='Unknown';$script:Model='Unknown'};if($script:Manufacturer -eq 'Microsoft Corporation' -and $script:Model -match 'Virtual|Virtual Machine'){$script:PlatformType='Virtual Machine'}else{$script:PlatformType='Physical PC'};$vp=Get-VendorProfile
  $script:Vendor=$vp.Vendor
  $script:VendorSite=$vp.Site
  $script:VendorNote=$vp.Note
  if($vp.Series){$script:Series=$vp.Series}
  Log "Detected vendor: $script:Manufacturer ($script:Vendor); model: $script:Model; platform: $script:PlatformType"}
function Get-VendorProfile{
  $m=[string]$script:Manufacturer
  $profiles=@(
    [pscustomobject]@{Match='hewlett|(^|[^a-z])hp([^\w]|$)|hp inc';Vendor='HP';Site='https://support.hp.com';Series=@('EliteBook','ProBook','ZBook','Spectre','Envy','Pavilion','Omen','OMEN','Victus','EliteDesk','ProDesk','EliteSlice');Note='HP Support Assistant, HP PC Hardware Diagnostics (F2 at boot)'}
    [pscustomobject]@{Match='dell|alienware';Vendor='Dell';Site='https://www.dell.com/support';Series=@('Latitude','Inspiron','OptiPlex','Precision','XPS','Vostro','Alienware','G15','G16','Dimension');Note='Dell SupportAssist, ePSA pre-boot diagnostics (F12)'}
    [pscustomobject]@{Match='lenovo|thinkpad|thinkcentre';Vendor='Lenovo';Site='https://support.lenovo.com';Series=@('ThinkPad','ThinkCentre','ThinkBook','IdeaPad','IdeaCentre','Yoga','Legion','LOQ','ThinkStation','Flex');Note='Lenovo Vantage, Lenovo Diagnostics (F10 on supported models)'}
    [pscustomobject]@{Match='acer|gateway|emachines|packard bell';Vendor='Acer Group';Site='https://www.acer.com/support';Series=@('Aspire','Swift','Spin','TravelMate','Predator','Nitro','Extensa','Veriton','ConceptD','Gateway','eMachines','Packard Bell');Note='Acer Care Center, Acer Quick Access'}
    [pscustomobject]@{Match='asus|asustek';Vendor='ASUS';Site='https://www.asus.com/support';Series=@('VivoBook','ZenBook','ExpertBook','ProArt','ROG','TUF','Chromebook','ProArt Studiobook','Zenbook');Note='MyASUS, ASUS Diagnostics'}
    [pscustomobject]@{Match='micro-star|msi';Vendor='MSI';Site='https://www.msi.com/support';Series=@('Katana','Raider','Titan','Stealth','Prestige','Modern','Cyborg','Vector','Crosshair','Curved');Note='MSI Center, MSI Diagnostic tools'}
    [pscustomobject]@{Match='microsoft|surface';Vendor='Microsoft Surface';Site='https://support.microsoft.com/surface';Series=@('Surface Pro','Surface Laptop','Surface Go','Surface Book','Surface Studio','Surface Duo');Note='Surface Diagnostic Toolkit, Windows Updatefirmware maintenance'}
    [pscustomobject]@{Match='samsung';Vendor='Samsung';Site='https://www.samsung.com/support';Series=@('Galaxy Book','Galaxy Book Pro','Galaxy Book Flex','Notebook','NP-');Note='Samsung Settings, Samsung Update'}
    [pscustomobject]@{Match='toshiba|dynabook';Vendor='Toshiba / Dynabook';Site='https://www.dynabook.com/support';Series=@('Satellite','Portege','Tecra','dynabook','Qosmio','KIRA');Note='Toshiba PC Health Monitor (older models)'}
    [pscustomobject]@{Match='fujitsu';Vendor='Fujitsu';Site='https://www.fujitsu.com/support';Series=@('LIFEBOOK','ESPRIMO','Stylistic','Celsius');Note='Fujitsu Diagnostic Tool, DeskUpdate'}
    [pscustomobject]@{Match='panasonic';Vendor='Panasonic';Site='https://panasonic.jp/toughbook';Series=@('Toughbook','Let','TOUGH');Note='Panasonic PC Settings, Toughbook Diagnostics'}
    [pscustomobject]@{Match='apple';Vendor='Apple (Windows on Mac)';Site='https://support.apple.com';Series=@('MacBook','iMac','Mac mini','Mac Pro','MacBook Air','MacBook Pro');Note='Boot Camp Software Update, Apple Diagnostics runs on macOS side'}
    [pscustomobject]@{Match='huawei';Vendor='HUAWEI';Site='https://consumer.huawei.com/support';Series=@('MateBook','MateBook D','MateBook X','MagicBook');Note='HUAWEI PC Manager'}
    [pscustomobject]@{Match='honor';Vendor='HONOR';Site='https://www.hihonor.com/support';Series=@('MagicBook','MagicBook Pro','Hunter');Note='HONOR PC Manager'}
    [pscustomobject]@{Match='xiaomi|redmi|timi|mitebook';Vendor='Xiaomi / Redmi';Site='https://www.mi.com/support';Series=@('Mi NoteBook','RedmiBook','MiBook','Xiaomi Book');Note='Xiaomi PC Manager (via Mi account)'}
    [pscustomobject]@{Match='lg electronics|lg(\s|$)';Vendor='LG';Site='https://www.lg.com/support';Series=@('Gram','UltraPC','Style');Note='LG Update Center, LG Smart Assistant'}
    [pscustomobject]@{Match='razer';Vendor='Razer';Site='https://support.razer.com';Series=@('Blade','Blade Stealth','Blade Pro','Book');Note='Razer Synapse, Razer Care'}
    [pscustomobject]@{Match='gigabyte';Vendor='GIGABYTE';Site='https://www.gigabyte.com/support';Series=@('AERO','AORUS','Gaming','G5','G6','G7');Note='GIGABYTE Control Center'}
    [pscustomobject]@{Match='vaio|sony';Vendor='VAIO / Sony';Site='https://support.vaio.com';Series=@('VAIO','SX','FE','FH','Pro');Note='VAIO Care, VAIO Update'}
    [pscustomobject]@{Match='medion';Vendor='Medion';Site='https://www.medion.com/support';Series=@('Akoya','Erazer','Lifetab');Note='Medion Service Center tools'}
    [pscustomobject]@{Match='clevo|tongfang|quanta|compal|pegatron|wistron| Inventec|system76|framework';Vendor='ODM / Custom-built (whitebook)';Site='https://www.google.com/search?q=PC+manufacturer+support';Series=@();Note='Generic Windows diagnostics; check seller/warranty documentation for vendor tools'}
  )
  $hit=$null
  foreach($p in $profiles){ if($m -match $p.Match){ $hit=$p; break } }
  if(-not $hit){ $hit=[pscustomobject]@{Match='';Vendor='Unknown (generic PC)';Site='https://www.google.com/search?q=PC+manufacturer+support';Series=@();Note='Generic Windows diagnostics work on every Windows 10/11 PC'} }
  $series=($hit.Series | Where-Object { $_ -and ($script:Model -match [regex]::Escape($_)) } | Select-Object -First 1)
  [pscustomobject]@{Vendor=$hit.Vendor;Site=$hit.Site;Series=$series;Note=$hit.Note}
}
function Show-VendorProfile{Header;Log "Viewed vendor profile ($($script:Vendor))";Write-Host '--- VENDOR SUPPORT PROFILE ---';Write-Host "Detected vendor : $script:Vendor";Write-Host "Manufacturer   : $script:Manufacturer";Write-Host "Model          : $script:Model";if($script:Series){Write-Host "Product series : $script:Series"};Write-Host "Support site   : $script:VendorSite";Write-Host "Vendor tools   : $script:VendorNote";Write-Host '';Write-Host 'Vendor-specific tools are OPTIONAL. All diagnostics in this';Write-Host 'toolkit use standard Windows APIs and work across vendors.';Pause-Toolkit}
function SystemInfo{Header;Log 'Viewed system information';$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$p=Get-CimInstance Win32_Processor|select -First 1;$b=Get-CimInstance Win32_BIOS|select -First 1;Write-Host "Computer : $env:COMPUTERNAME";Write-Host "User     : $env:USERNAME";Write-Host "Vendor   : $($c.Manufacturer)";Write-Host "Model    : $($c.Model)";Write-Host "Platform : $script:PlatformType";Write-Host "OS       : $($o.Caption)";Write-Host "Build    : $($o.BuildNumber)";Write-Host "CPU      : $($p.Name)";Write-Host "Cores    : $($p.NumberOfCores)";Write-Host "Threads  : $($p.NumberOfLogicalProcessors)";Write-Host ('RAM      : {0:N2} GB' -f ($c.TotalPhysicalMemory/1GB));Write-Host "BIOS     : $($b.Manufacturer) $($b.SMBIOSBIOSVersion)";Write-Host "Admin    : $(Admin)";Write-Host "Vendor   : $script:Vendor";if($script:Series){Write-Host "Series   : $script:Series"};Write-Host "Support  : $script:VendorSite";Pause-Toolkit}
function Hardware{Header;Log 'Ran hardware diagnostics';Write-Host '--- Problem Devices ---';$x=Get-PnpDevice|where Status -ne 'OK';if($x){$x|ft Status,Class,FriendlyName -AutoSize}else{Write-Host '[OK] No PnP devices currently report a problem.'};Write-Host "`n--- CPU ---";Get-CimInstance Win32_Processor|select Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed|ft -AutoSize;Write-Host "`n--- Memory ---";Get-CimInstance Win32_PhysicalMemory|select Manufacturer,PartNumber,@{N='CapacityGB';E={[math]::Round($_.Capacity/1GB,2)}},Speed|ft -AutoSize;Write-Host "`n--- GPU ---";Get-CimInstance Win32_VideoController|select Name,DriverVersion,Status|ft -AutoSize;Write-Host "`n--- USB ---";Get-PnpDevice -Class USB|select Status,FriendlyName,InstanceId|ft -AutoSize;Write-Host "`n--- Network Adapters ---";Get-NetAdapter|select Name,Status,LinkSpeed,InterfaceDescription|ft -AutoSize;Pause-Toolkit}
function Network{Header;Log 'Ran network diagnostics';Write-Host '--- Configuration ---';Get-NetIPConfiguration|select InterfaceAlias,IPv4Address,IPv4DefaultGateway,DNSServer|fl;Write-Host '--- Connectivity ---';foreach($t in '127.0.0.1','8.8.8.8'){if(Test-Connection $t -Count 2 -Quiet){Write-Host "[OK] $t reachable"}else{Write-Host "[FAIL] $t unreachable"}};Write-Host '--- DNS ---';try{Resolve-DnsName example.com -ErrorAction Stop|select -First 3 Name,Type,IPAddress|ft -AutoSize;Write-Host '[OK] DNS resolution works.'}catch{Write-Host '[FAIL] DNS resolution failed.'};Write-Host '--- HTTPS test ---';if(Test-NetConnection example.com -Port 443 -InformationLevel Quiet){Write-Host '[OK] HTTPS connection works.'}else{Write-Host '[FAIL] HTTPS connection failed.'};Write-Host '--- Route ---';route print;Pause-Toolkit}
function NetworkWizard{Header;Log 'Ran network troubleshooting wizard';$score=0;$checks=@();Write-Host 'NETWORK TROUBLESHOOTING WIZARD';Write-Host 'Running guided checks...`n';$adapters=Get-NetAdapter|where Status -eq 'Up';if($adapters){Write-Host '[OK] Network adapter is active.';$score++}else{Write-Host '[FAIL] No active network adapter found.';$checks+='Check Wi-Fi/Ethernet adapter and driver.'};$cfg=Get-NetIPConfiguration|where IPv4DefaultGateway;if($cfg){Write-Host '[OK] Default gateway detected.';$score++}else{Write-Host '[FAIL] No default gateway detected.';$checks+='Check DHCP/router connection.'};if(Test-Connection 8.8.8.8 -Count 2 -Quiet){Write-Host '[OK] Internet IP connectivity works.';$score++}else{Write-Host '[FAIL] Internet IP connectivity failed.';$checks+='Check router, ISP, or firewall.'};try{Resolve-DnsName example.com -ErrorAction Stop|Out-Null;Write-Host '[OK] DNS resolution works.';$score++}catch{Write-Host '[FAIL] DNS resolution failed.';$checks+='Check DNS settings or DNS server.'};if(Test-NetConnection example.com -Port 443 -InformationLevel Quiet){Write-Host '[OK] HTTPS connectivity works.';$score++}else{Write-Host '[FAIL] HTTPS connectivity failed.';$checks+='Check proxy, firewall, or HTTPS connectivity.'};Write-Host "`nScore: $score / 5";if($checks){Write-Host "`nRecommendations:";$checks|select -Unique|%{Write-Host " - $_"}}else{Write-Host '[GOOD] Basic network path looks healthy.'};Pause-Toolkit}
function WindowsHealth{Header;Log 'Ran Windows health diagnostics';Write-Host '--- SFC verification (read-only) ---';sfc /verifyonly;Write-Host '--- DISM CheckHealth ---';dism /Online /Cleanup-Image /CheckHealth;Write-Host '--- Recent System Errors ---';Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-3)} -MaxEvents 15|select TimeCreated,Id,ProviderName,LevelDisplayName,Message|fl;Write-Host '--- Services not running (selected automatic services) ---';Get-CimInstance Win32_Service|where {$_.StartMode -eq 'Auto' -and $_.State -ne 'Running'}|select Name,DisplayName,StartMode,State|ft -AutoSize;Pause-Toolkit}
function WindowsUpdate{Header;Log 'Ran Windows Update diagnostics';Write-Host '--- Windows Update Services ---';foreach($n in 'wuauserv','bits','cryptsvc','UsoSvc'){ $s=Get-Service $n; if($s){Write-Host ("{0}: {1} ({2})" -f $n,$s.Status,$s.StartType)}else{Write-Host "${n}: unavailable"}};Write-Host "`n--- Recent Update History ---";try{Get-HotFix|Sort-Object InstalledOn -Descending|select -First 10 HotFixID,InstalledOn,Description|ft -AutoSize}catch{Write-Host '[INFO] HotFix history unavailable.'};Write-Host "`n--- Update Cache ---";$cache=Join-Path $env:windir 'SoftwareDistribution';if(Test-Path $cache){$size=(Get-ChildItem $cache -Recurse -Force -ErrorAction SilentlyContinue|Measure-Object Length -Sum).Sum/1MB;Write-Host ('SoftwareDistribution size: {0:N1} MB' -f $size)};Write-Host "`nRecommendations:";Write-Host ' - If updates fail, record the error code before resetting services/cache.';Write-Host ' - Use Repair Center only with authorization.';Pause-Toolkit}
function Storage{Header;Log 'Ran storage diagnostics';Write-Host '--- Volumes ---';Get-Volume|select DriveLetter,FileSystem,HealthStatus,@{N='FreeGB';E={[math]::Round($_.SizeRemaining/1GB,2)}},@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}}|ft -AutoSize;Write-Host "`n--- Physical Disks ---";Get-PhysicalDisk|select FriendlyName,MediaType,HealthStatus,OperationalStatus,@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}}|ft -AutoSize;Write-Host "`n--- CHKDSK C: (read-only) ---";chkdsk C:;Pause-Toolkit}
function StorageAdvanced{Header;Log 'Ran advanced storage diagnostics';Write-Host '--- Disk Health ---';Get-Disk|select Number,FriendlyName,BusType,OperationalStatus,HealthStatus,@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}}|ft -AutoSize;Write-Host "`n--- Physical Disk Reliability (when supported) ---";try{Get-PhysicalDisk|Get-StorageReliabilityCounter|select DeviceId,Temperature,ReadErrorsTotal,WriteErrorsTotal,PowerOnHours,Wear|ft -AutoSize}catch{Write-Host '[INFO] Reliability counters are not available on this system.'};Write-Host "`n--- Volumes with low free space (<10%) ---";$low=Get-Volume|where {$_.Size -gt 0 -and ($_.SizeRemaining/$_.Size) -lt .10};if($low){$low|select DriveLetter,FileSystem,HealthStatus,@{N='FreeGB';E={[math]::Round($_.SizeRemaining/1GB,2)}},@{N='FreePercent';E={[math]::Round(($_.SizeRemaining/$_.Size)*100,1)}}|ft -AutoSize;Write-Host '[WARNING] Consider freeing space before major repairs.'}else{Write-Host '[OK] No volume is below 10% free space.'};Write-Host "`nNote: Storage health information depends on hardware and Windows support.";Pause-Toolkit}
function Drivers{Header;Log 'Ran driver diagnostics';Write-Host '--- Signed Driver Summary ---';driverquery /si;Write-Host "`n--- Problem Devices ---";Get-PnpDevice|where Status -ne 'OK'|select Status,Class,FriendlyName,InstanceId|ft -AutoSize;Write-Host "`n--- Driver Packages ---";pnputil /enum-drivers;Pause-Toolkit}
function Battery{Header;Log 'Ran battery diagnostics';$b=Get-CimInstance Win32_Battery;if($b){$b|select Name,BatteryStatus,EstimatedChargeRemaining,EstimatedRunTime|ft -AutoSize;Write-Host 'Generating Windows battery report...';$f=Join-Path $ReportDir ("battery_{0}.html" -f (Get-Date -Format 'yyyyMMdd_HHmmss'));powercfg /batteryreport /output $f|Out-Null;Write-Host "[OK] $f"}else{Write-Host '[INFO] No battery detected. This may be a desktop PC.'};Pause-Toolkit}
function Security{Header;Log 'Viewed security status';Write-Host '--- Firewall ---';Get-NetFirewallProfile|select Name,Enabled,DefaultInboundAction,DefaultOutboundAction|ft -AutoSize;Write-Host '--- Microsoft Defender ---';if(Get-Command Get-MpComputerStatus){Get-MpComputerStatus|select AMServiceEnabled,AntivirusEnabled,RealTimeProtectionEnabled,AntispywareEnabled,AntivirusSignatureVersion|ft -AutoSize}else{Write-Host '[INFO] Defender cmdlets unavailable.'};Pause-Toolkit}
function ErrorAnalyzer{Header;Log 'Ran Windows error analyzer';Write-Host 'WINDOWS ERROR ANALYZER';$events=Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-3)} -MaxEvents 20;if(-not $events){Write-Host '[OK] No critical/error System events found in the last 3 days.';Pause-Toolkit;return};$groups=$events|Group-Object Id|Sort-Object Count -Descending;foreach($g in $groups){$e=$g.Group|Select-Object -First 1;Write-Host "`nID $($g.Name) — $($g.Count) occurrence(s) — $($e.ProviderName)";Write-Host "Message: $($e.Message -replace '\s+',' ')";switch([int]$g.Name){41{Write-Host 'Possible cause: unexpected shutdown or power/hardware event.';Write-Host 'Recommended action: check power, thermal conditions, and recent hardware/driver changes.'}7{Write-Host 'Possible cause: storage/controller event.';Write-Host 'Recommended action: run storage diagnostics and back up important data.'}1001{Write-Host 'Possible cause: Windows Error Reporting event.';Write-Host 'Recommended action: inspect the related application/system event and recent changes.'}default{Write-Host 'Recommended action: review the event provider/message and correlate with the time of the problem.'}}};Pause-Toolkit}
function Repair{Header;Write-Host 'REPAIR CENTER - system changes require authorization.';if(-not(Admin)){Write-Host '[WARNING] Administrator privileges are recommended for repairs.'};Write-Host '1 Flush DNS';Write-Host '2 Renew DHCP';Write-Host '3 Reset Winsock';Write-Host '4 Reset TCP/IP';Write-Host '5 DISM RestoreHealth';Write-Host '6 SFC Scan';Write-Host '7 Restart Windows Explorer';Write-Host '8 Restart Windows Update services';Write-Host '9 Reset Windows Update cache';Write-Host '0 Back';$c=Read-Host 'Choose';switch($c){'1'{if(Confirm 'Flush DNS cache?'){ipconfig /flushdns;Log 'Flushed DNS'}}'2'{if(Confirm 'Release and renew DHCP?'){ipconfig /release;ipconfig /renew;Log 'Renewed DHCP'}}'3'{if(Confirm 'Reset Winsock? A restart may be required.'){netsh winsock reset;Log 'Reset Winsock'}}'4'{if(Confirm 'Reset TCP/IP? A restart may be required.'){netsh int ip reset;Log 'Reset TCP/IP'}}'5'{if(Confirm 'Run DISM RestoreHealth? This can take time.'){dism /Online /Cleanup-Image /RestoreHealth;Log 'Ran DISM RestoreHealth'}}'6'{if(Confirm 'Run SFC /scannow?'){sfc /scannow;Log 'Ran SFC scan'}}'7'{if(Confirm 'Restart Windows Explorer?'){Stop-Process -Name explorer -Force;Start-Process explorer.exe;Log 'Restarted Explorer'}}'8'{if(Confirm 'Restart Windows Update services?'){foreach($n in 'wuauserv','bits','cryptsvc','UsoSvc'){Restart-Service $n -Force};Log 'Restarted Windows Update services'}}'9'{if(-not(Admin)){Write-Host '[WARNING] Run the toolkit as Administrator for this action.'}elseif(Confirm 'Reset Windows Update cache? This renames the SoftwareDistribution folder.'){Stop-Service wuauserv,bits,cryptsvc -Force;Rename-Item (Join-Path $env:windir 'SoftwareDistribution') ("SoftwareDistribution.old_{0}" -f (Get-Date -Format 'yyyyMMddHHmmss'));Start-Service cryptsvc,bits,wuauserv;Log 'Reset Windows Update cache'}}};Pause-Toolkit}
function GetReportData{$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$p=Get-CimInstance Win32_Processor|select -First 1;[ordered]@{Toolkit=$Name;Version=$Version;CaseId=$CaseId;CreatedBy=$Author;Generated=(Get-Date);Computer=$env:COMPUTERNAME;User=$env:USERNAME;Administrator=(Admin);Manufacturer=$c.Manufacturer;Model=$c.Model;PlatformType=$script:PlatformType;Vendor=$script:Vendor;VendorSite=$script:VendorSite;OS=$o.Caption;Build=$o.BuildNumber;CPU=$p.Name;RAMGB=[math]::Round($c.TotalPhysicalMemory/1GB,2);Disks=@(Get-Disk|select Number,FriendlyName,BusType,HealthStatus,OperationalStatus,@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}});Volumes=@(Get-Volume|select DriveLetter,FileSystem,HealthStatus,@{N='FreeGB';E={[math]::Round($_.SizeRemaining/1GB,2)}},@{N='SizeGB';E={[math]::Round($_.Size/1GB,2)}});ProblemDevices=@(Get-PnpDevice|where Status -ne 'OK'|select Status,Class,FriendlyName);Network=@(Get-NetIPConfiguration|select InterfaceAlias,IPv4Address,IPv4DefaultGateway,DNSServer)}}
function Report{Header;$d=GetReportData;$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$txt=Join-Path $ReportDir ("diagnostic_{0}.txt" -f $stamp);$json=Join-Path $ReportDir ("diagnostic_{0}.json" -f $stamp);$html=Join-Path $ReportDir ("diagnostic_{0}.html" -f $stamp);$summary=if($d.ProblemDevices.Count -gt 0){'WARNING - problem devices detected'}else{'GOOD - no PnP problem devices detected'};@("$Name v$Version","Case ID: $CaseId","Created by: $Author","Generated: $($d.Generated)","Computer: $($d.Computer)","Vendor: $($d.Manufacturer)","Model: $($d.Model)","Platform: $($d.PlatformType)","User: $($d.User)","Administrator: $($d.Administrator)","Health summary: $summary",'','=== OS ===',(Get-CimInstance Win32_OperatingSystem|select Caption,Version,BuildNumber,OSArchitecture,LastBootUpTime|fl|Out-String),'=== COMPUTER ===',(Get-CimInstance Win32_ComputerSystem|select Manufacturer,Model,SystemType,TotalPhysicalMemory|fl|Out-String),'=== CPU ===',(Get-CimInstance Win32_Processor|select Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed|fl|Out-String),'=== DISKS ===',($d.Disks|ft -AutoSize|Out-String),'=== VOLUMES ===',($d.Volumes|ft -AutoSize|Out-String),'=== NETWORK ===',($d.Network|fl|Out-String),'=== PROBLEM DEVICES ===',($d.ProblemDevices|ft -AutoSize|Out-String))|Set-Content $txt -Encoding UTF8;$d|ConvertTo-Json -Depth 6|Set-Content $json -Encoding UTF8;$body=($d|ConvertTo-Html -Title "$Name v$Version - $CaseId" -PreContent "<h1>$Name v$Version</h1><p><b>Case ID:</b> $CaseId</p><p><b>Vendor:</b> $($d.Manufacturer)</p><p><b>Model:</b> $($d.Model)</p><p><b>Platform:</b> $($d.PlatformType)</p><p><b>Health summary:</b> $summary</p>" -PostContent '<p>Generated locally by Arcange Windows Technician Toolkit.</p>');$body|Set-Content $html -Encoding UTF8;Log "Generated reports: $txt, $json, $html";Write-Host "[OK] TXT report:  $txt";Write-Host "[OK] JSON report: $json";Write-Host "[OK] HTML report: $html";Write-Host "Health summary: $summary";Pause-Toolkit}
function Main{Initialize-HardwareProfile;if(-not(Supported)){Header;Write-Host '[UNSUPPORTED OS] Windows 10 and Windows 11 only.';Pause-Toolkit;return};if($Section){Log "Section shortcut requested: $Section";switch($Section){'SystemInfo'{SystemInfo}'Hardware'{Hardware}'Network'{Network}'NetworkWizard'{NetworkWizard}'WindowsHealth'{WindowsHealth}'WindowsUpdate'{WindowsUpdate}'Storage'{Storage}'StorageAdvanced'{StorageAdvanced}'Drivers'{Drivers}'Battery'{Battery}'Security'{Security}'ErrorAnalyzer'{ErrorAnalyzer}'Repair'{Repair}'Report'{Report}'VendorProfile'{Show-VendorProfile}default{Header;Write-Host "[INFO] Unknown section '$Section' - opening full menu.";Pause-Toolkit;}};return};Log "Toolkit started on $env:COMPUTERNAME ($script:Manufacturer $script:Model)";while($true){Header;Write-Host ' 1. System Information';Write-Host ' 2. Hardware Diagnostics';Write-Host ' 3. Network Diagnostics';Write-Host ' 4. Network Troubleshooting Wizard';Write-Host ' 5. Windows Health Diagnostics';Write-Host ' 6. Windows Update Diagnostics';Write-Host ' 7. Storage Diagnostics';Write-Host ' 8. Advanced Storage Diagnostics';Write-Host ' 9. Driver Diagnostics';Write-Host '10. Battery Diagnostics';Write-Host '11. Security Status';Write-Host '12. Windows Error Analyzer';Write-Host '13. Repair Center';Write-Host '14. Generate Full Diagnostic Reports';Write-Host '15. Open Reports Folder';Write-Host '16. Vendor Support Profile';Write-Host ' 0. Exit';Write-Host '';Write-Host "Administrator: $(Admin)";$c=Read-Host 'Select an option';switch($c){'1'{SystemInfo}'2'{Hardware}'3'{Network}'4'{NetworkWizard}'5'{WindowsHealth}'6'{WindowsUpdate}'7'{Storage}'8'{StorageAdvanced}'9'{Drivers}'10'{Battery}'11'{Security}'12'{ErrorAnalyzer}'13'{Repair}'14'{Report}'15'{Start-Process explorer.exe $ReportDir}'16'{Show-VendorProfile}'0'{Header;Write-Host '============================================================';Write-Host '          THANK YOU FOR USING THIS SERVICE';Write-Host '============================================================';Write-Host "$Name v$Version";Write-Host "Case ID: $CaseId";Write-Host "Vendor: $script:Manufacturer";Write-Host "Model: $script:Model";Write-Host '';Write-Host 'Thank you for using this service!';Write-Host 'Please keep your reports for future troubleshooting.';Log 'Toolkit session ended';return}default{Write-Host '[!] Invalid option.';Start-Sleep 1}}}}
Main
