#requires -version 5.1
[CmdletBinding()]
param()
$ErrorActionPreference='SilentlyContinue'
$Version='0.1'; $Author='Mukamyi Izere Arcange'; $Name='Arcange Windows Technician Toolkit'
$Root=Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$ReportDir=Join-Path $Root 'reports'; New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
$LogFile=Join-Path $ReportDir ("session_{0}.log" -f (Get-Date -Format 'yyyyMMdd_HHmmss'))
function Log($m,$l='INFO'){Add-Content $LogFile ("{0} [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$l,$m)}
function Header{Clear-Host;Write-Host '';Write-Host '============================================================';Write-Host "       ARCANGE WINDOWS TECHNICIAN TOOLKIT v$Version";Write-Host '============================================================';Write-Host "Created by: $Author";Write-Host 'Supported OS: Windows 10 and Windows 11';Write-Host '============================================================';Write-Host ''}
function Pause-Toolkit{Read-Host 'Press Enter to continue'|Out-Null}
function Supported{$o=Get-CimInstance Win32_OperatingSystem;return [bool]($o.Caption -match 'Windows 10|Windows 11')}
function SystemInfo{Header;Log 'Viewed system information';$o=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;$p=Get-CimInstance Win32_Processor|select -First 1;$b=Get-CimInstance Win32_BIOS|select -First 1;Write-Host "Computer : $env:COMPUTERNAME";Write-Host "User     : $env:USERNAME";Write-Host "OS       : $($o.Caption)";Write-Host "Build    : $($o.BuildNumber)";Write-Host "CPU      : $($p.Name)";Write-Host "Cores    : $($p.NumberOfCores)";Write-Host "Threads  : $($p.NumberOfLogicalProcessors)";Write-Host ('RAM      : {0:N2} GB' -f ($c.TotalPhysicalMemory/1GB));Write-Host "BIOS     : $($b.Manufacturer) $($b.SMBIOSBIOSVersion)";Write-Host "Model    : $($c.Manufacturer) $($c.Model)";Pause-Toolkit}
function Hardware{Header;Log 'Ran hardware diagnostics';Write-Host '--- Problem Devices ---';$x=Get-PnpDevice|where Status -ne 'OK';if($x){$x|ft -AutoSize}else{Write-Host '[OK] No PnP devices currently report a problem.'};Write-Host '`n--- CPU ---';Get-CimInstance Win32_Processor|select Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed|ft -AutoSize;Write-Host '`n--- Memory ---';Get-CimInstance Win32_PhysicalMemory|select Manufacturer,PartNumber,Capacity,Speed|ft -AutoSize;Write-Host '`n--- GPU ---';Get-CimInstance Win32_VideoController|select Name,DriverVersion,Status|ft -AutoSize;Write-Host '`n--- Network Adapters ---';Get-NetAdapter|select Name,Status,LinkSpeed,InterfaceDescription|ft -AutoSize;Pause-Toolkit}
function Network{Header;Log 'Ran network diagnostics';Write-Host '--- Configuration ---';Get-NetIPConfiguration|select InterfaceAlias,IPv4Address,IPv4DefaultGateway,DNSServer|fl;Write-Host '--- Connectivity ---';foreach($t in '127.0.0.1','8.8.8.8'){if(Test-Connection $t -Count 2 -Quiet){Write-Host "[OK] $t reachable"}else{Write-Host "[FAIL] $t unreachable"}};Write-Host '--- DNS ---';try{Resolve-DnsName example.com -ErrorAction Stop|select -First 3 Name,Type,IPAddress|ft -AutoSize;Write-Host '[OK] DNS resolution works.'}catch{Write-Host '[FAIL] DNS resolution failed.'};Write-Host '--- Route ---';route print;Pause-Toolkit}
function WindowsHealth{Header;Write-Host '--- SFC (read-only verification) ---';sfc /verifyonly;Write-Host '--- DISM CheckHealth ---';dism /Online /Cleanup-Image /CheckHealth;Write-Host '--- Recent System Errors ---';Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-3)} -MaxEvents 15|select TimeCreated,Id,ProviderName,LevelDisplayName,Message|fl;Pause-Toolkit}
function Storage{Header;Log 'Ran storage diagnostics';Get-Volume|select DriveLetter,FileSystem,HealthStatus,SizeRemaining,Size|ft -AutoSize;Write-Host '--- Physical Disks ---';Get-PhysicalDisk|select FriendlyName,MediaType,HealthStatus,OperationalStatus,Size|ft -AutoSize;Write-Host '--- CHKDSK C: (read-only) ---';chkdsk C:;Pause-Toolkit}
function Repair{Header;Write-Host 'REPAIR CENTER - system changes require technician authorization.';Write-Host '1 Flush DNS';Write-Host '2 Renew DHCP';Write-Host '3 Reset Winsock';Write-Host '4 Reset TCP/IP';Write-Host '5 DISM RestoreHealth';Write-Host '6 SFC Scan';Write-Host '0 Back';$c=Read-Host 'Choose';switch($c){'1'{ipconfig /flushdns;Log 'Flushed DNS'}'2'{ipconfig /release;ipconfig /renew;Log 'Renewed DHCP'}'3'{netsh winsock reset;Log 'Reset Winsock'}'4'{netsh int ip reset;Log 'Reset TCP/IP'}'5'{dism /Online /Cleanup-Image /RestoreHealth;Log 'Ran DISM RestoreHealth'}'6'{sfc /scannow;Log 'Ran SFC'}};Pause-Toolkit}
function Report{Header;$f=Join-Path $ReportDir ("diagnostic_{0}.txt" -f (Get-Date -Format 'yyyyMMdd_HHmmss'));Log "Generated report $f";@("$Name v$Version","Created by: $Author","Generated: $(Get-Date)","Computer: $env:COMPUTERNAME",'', '=== OS ===',(Get-CimInstance Win32_OperatingSystem|fl *|Out-String),'=== COMPUTER ===',(Get-CimInstance Win32_ComputerSystem|fl *|Out-String),'=== CPU ===',(Get-CimInstance Win32_Processor|fl *|Out-String),'=== BIOS ===',(Get-CimInstance Win32_BIOS|fl *|Out-String),'=== MEMORY ===',(Get-CimInstance Win32_PhysicalMemory|ft Manufacturer,PartNumber,Capacity,Speed|Out-String),'=== DISKS ===',(Get-Disk|ft Number,FriendlyName,OperationalStatus,HealthStatus,Size|Out-String),'=== NETWORK ===',(Get-NetIPConfiguration|fl|Out-String),'=== ADAPTERS ===',(Get-NetAdapter|ft Name,Status,LinkSpeed,InterfaceDescription|Out-String),'=== PROBLEM DEVICES ===',((Get-PnpDevice|where Status -ne 'OK')|ft Status,Class,FriendlyName,InstanceId|Out-String),'=== FIREWALL ===',(Get-NetFirewallProfile|ft Name,Enabled,DefaultInboundAction,DefaultOutboundAction|Out-String))|Set-Content $f -Encoding UTF8;Write-Host "[OK] Report saved: $f";Pause-Toolkit}
function Main{if(-not(Supported)){Header;Write-Host '[UNSUPPORTED OS] Windows 10 and Windows 11 only.';Pause-Toolkit;return};while($true){Header;Write-Host '1 System Information';Write-Host '2 Hardware Diagnostics';Write-Host '3 Network Diagnostics';Write-Host '4 Windows Health Diagnostics';Write-Host '5 Storage Diagnostics';Write-Host '6 Repair Center';Write-Host '7 Generate Full Diagnostic Report';Write-Host '8 Open Reports Folder';Write-Host '0 Exit';$c=Read-Host 'Select an option';switch($c){'1'{SystemInfo}'2'{Hardware}'3'{Network}'4'{WindowsHealth}'5'{Storage}'6'{Repair}'7'{Report}'8'{Start-Process explorer.exe $ReportDir}'0'{Header;Write-Host '============================================================';Write-Host '          THANK YOU FOR USING THIS SERVICE';Write-Host '============================================================';Write-Host "Created by: $Author";Write-Host 'Thank you for using Arcange Windows Technician Toolkit!';Log 'Toolkit session ended';return}default{Write-Host '[!] Invalid option.';Start-Sleep 1}}}}
Log 'Toolkit started';Main
